name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  create-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker image locally
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hello-world:latest --tag hello-world:1.5 .

      # Step 3: Push image to Docker Hub
      - name: Push to Docker Hub
        uses: viktordeilert/dockerhub-buildpush@v1.1
        with:
          registry_url: docker.io
          repository_name: viktordeilert/vdeilert
          user_name: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_version: latest
          docker_file: Dockerfile
